# Stop dev env every day

name: Cron Stop Dev Env

on:
  schedule:
    - cron: "30 00 * * *"

jobs:
  manage-dev-env:
    runs-on: ubuntu-latest
    steps:
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: 'eu-west-3'
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
    - name: Stop env
      uses: flyweightrocks/aws-ec2-action@v1
      with:
        instance-id: ${{ secrets.DEV_INSTANCES_ID_LIST }}
        stop-instance: true
