# Start or stop dev env

name: Manage Dev Env

on:
  workflow_dispatch:
    inputs:
      state:
        description: 'Requested state'
        required: true
        default: 'start'
        type: choice
        options:
          - start
          - stop

jobs:
  manage-dev-env:
    runs-on: ubuntu-latest
    steps:
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: 'eu-west-3'
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
    - name: Start/Stop env
      uses: flyweightrocks/aws-ec2-action@v1
      with:
        instance-id: ${{ secrets.DEV_INSTANCES_ID_LIST }}
        wait-instance-running: ${{ inputs.state == 'start' }}
        stop-instance: ${{ inputs.state == 'stop' }}
